//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epicode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationID { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationBody { get; set; }
        public string NotificationRecipient { get; set; }
        public string NotificatonRecipientName { get; set; }
        public short NotificationRetries { get; set; }
        public short FK_NotificationTypeID { get; set; }
        public short FK_NotificationSourceID { get; set; }
        public short FK_NotificationStatusID { get; set; }
        public string Note { get; set; }
        public System.DateTime DateTimeCaptured { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual NotificationSource NotificationSource { get; set; }
        public virtual NotificationStatus NotificationStatus { get; set; }
        public virtual NotificatonType NotificatonType { get; set; }
    }
}
