//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epicode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationStatus
    {
        public NotificationStatus()
        {
            this.Notification = new HashSet<Notification>();
        }
    
        public short NotificationStatusID { get; set; }
        public string NotificationStatusName { get; set; }
    
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
